name: Auto Branch on Issue

on:
  issues:
    types: [opened, labeled]

jobs:
  create-branch:
    if: >
      github.event.action == 'opened' ||
      (github.event.action == 'labeled' && github.event.label.name == 'dev')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write   # needed to create PR

    steps:
      - name: Check if issue has dev label
        id: label_check
        run: |
          has_label=false
          if [ "${{ github.event.action }}" = "labeled" ]; then
            if [ "${{ github.event.label.name }}" = "dev" ]; then
              has_label=true
            fi
          else
            for label in $(jq -r '.issue.labels[].name' <<< '${{ toJson(github.event.issue) }}'); do
              if [ "$label" = "dev" ]; then
                has_label=true
              fi
            done
          fi
          echo "has_label=$has_label" >> "$GITHUB_OUTPUT"

      - name: Checkout
        if: steps.label_check.outputs.has_label == 'true'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create branch from master (idempotent)
        if: steps.label_check.outputs.has_label == 'true'
        run: |
          set -euo pipefail

          ISSUE_NUMBER='${{ github.event.issue.number }}'
          ISSUE_TITLE='${{ github.event.issue.title }}'

          SLUG=$(printf "%s" "$ISSUE_TITLE" \
            | iconv -t ascii//TRANSLIT 2>/dev/null \
            | tr '[:upper:]' '[:lower:]' \
            | tr -cs 'a-z0-9' '-' \
            | sed 's/^-//;s/-$//')
          SLUG=${SLUG:0:50}

          BRANCH_NAME="dev/${ISSUE_NUMBER}-${SLUG}"

          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

          git config user.name "github-actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch --prune origin

          if git ls-remote --exit-code --heads origin "$BRANCH_NAME" >/dev/null 2>&1; then
            echo "Branch '$BRANCH_NAME' already exists on origin."
            exit 0
          fi

          git checkout -b "$BRANCH_NAME" origin/master
          git push -u origin "$BRANCH_NAME"

      - name: Create draft PR linked to issue
        if: steps.label_check.outputs.has_label == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.issue.number
            const branch_name = process.env.BRANCH_NAME

            // check if PR already exists for this branch
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${branch_name}`,
              state: "open"
            })
            if (prs.length > 0) {
              core.info(`PR already exists for branch ${branch_name}`)
              return
            }

            await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: branch_name,
              base: "master",
              title: `Draft: ${branch_name}`,
              body: `Linked to #${issue_number}`,
              draft: true
            })
