# .github/workflows/weekly-dev-to-main-pr.yml
name: Weekly PR dev → main

on:
  schedule:
    # Every Monday @ 06:00 UTC (08:00 Europe/Belgrade while DST)
    - cron: '0 20 * * 1'
  workflow_dispatch: {}   # allow manual run

permissions:
  contents: read
  pull-requests: write

jobs:
  weekly-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch branches
        run: |
          git fetch origin main:origin/main
          git fetch origin dev:origin/dev

      - name: Check if dev is ahead of main
        id: ahead
        run: |
          # Count commits: A = ahead of main, B = ahead of dev (divergence)
          read A B <<<"$(git rev-list --left-right --count origin/main...origin/dev)"
          echo "ahead_of_main=$A" >> "$GITHUB_OUTPUT"
          echo "ahead_of_dev=$B"  >> "$GITHUB_OUTPUT"
          echo "dev_ahead_commits=$A"
          echo "main_ahead_commits=$B"

      - name: Stop if nothing to promote
        if: steps.ahead.outputs.ahead_of_main == '0'
        run: echo "No new commits on dev compared to main. Skipping."

      - name: Create or update PR dev → main
        if: steps.ahead.outputs.ahead_of_main != '0'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # If a PR from dev→main already exists, just comment & exit.
          if gh pr list --state open --base main --head dev --json number | jq -e 'length>0' >/dev/null; then
            PRNUM=$(gh pr list --state open --base main --head dev --json number -q '.[0].number')
            gh pr comment "$PRNUM" --body "Weekly check: dev is ahead. Keeping this PR open for review."
            echo "PR #$PRNUM already open."
          else
            gh pr create \
              --base main \
              --head dev \
              --title "Weekly promotion: dev → main" \
              --body "Automated weekly PR. Review & merge to promote latest changes to production." \
              --label release
            echo "Created PR from dev to main."
          fi
